[Unit]
Description=tracker
After=network.target

[Service]
User=tracker
Group=tracker
WorkingDirectory=/var/www/tracker
Environment="PATH=/var/www/tracker/.venv/bin"
ExecStart=/var/www/tracker/.venv/bin/gunicorn main:app --bind 127.0.0.1:5004 --workers 1 --threads 8 --timeout 30 --log-level warning --access-logfile /var/log/tracker/tracker_access.log --error-logfile /var/log/tracker/tracker_error.log
Restart=always
TimeoutStopSec=1

[Install]
WantedBy=multi-user.target
